name: Catchy-Watch CI

on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.18'

      - name: Install pnpm
        run: npm install -g pnpm@latest-10

      - name: Restore Cypress binary cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install

      - name: Install Cypress binary
        run: pnpm exec cypress install

      - name: Run linter
        run: pnpm run lint

      - name: Run Cypress component tests
        run: pnpm run cypress:run

      - name: Build app
        run: pnpm run build
